# Generated by Django 3.1.5 on 2021-01-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0008_auto_20210129_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Electronic', 'Electronic'), ('Clothing', 'Clothing'), ('Automobiles', 'Automobiles'), ('Sport', 'Sport'), ('Books', 'Books'), ('Services', 'Services'), ('Other', 'Other')], default='Electronic', max_length=30),
            preserve_default=False,
        ),
    ]
