# Generated by Django 3.1.5 on 2021-02-05 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0017_auto_20210205_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productviews',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainsite.product'),
        ),
    ]
