# Generated by Django 3.1.5 on 2021-02-05 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0018_auto_20210205_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productviews',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='views',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainsite.productviews'),
            preserve_default=False,
        ),
    ]
