# Generated by Django 3.1.5 on 2021-02-05 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0020_auto_20210205_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Electronic', 'Electronic'), ('Clothing', 'Clothing'), ('Automobiles', 'Automobiles'), ('Sport', 'Sport'), ('Books', 'Books'), ('Services', 'Services'), ('Other', 'Other'), ('Most viewed', 'Most viewed')], max_length=30),
        ),
    ]
