# Generated by Django 3.1.5 on 2021-02-05 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0022_auto_20210205_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='city',
            field=models.CharField(default='Varna', max_length=30),
            preserve_default=False,
        ),
    ]
