# Generated by Django 3.1.5 on 2021-02-07 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0023_product_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_cost',
            field=models.IntegerField(default=0),
        ),
    ]
