# Generated by Django 3.1.5 on 2021-02-08 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0025_order_total_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Electronic', 'Electronic'), ('Clothing', 'Clothing'), ('Automobiles', 'Automobiles'), ('Sport', 'Sport'), ('Books', 'Books'), ('Services', 'Services'), ('Other', 'Other')], max_length=30),
        ),
    ]
